apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework
  labels:
    app: homework
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
      - name: homework
        image: homework:0.0.1
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          periodSeconds: 1
